name: Caching Primes

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Cache Primes
      id: cache-primes
      uses: actions/cache@v2
      with:
        path: /usr/local/include/U*
        key: ${{ runner.os }}-primes
    - name: Generate Prime Numbers
      if: steps.cache-primes.outputs.cache-hit != 'true'
      run: |
        sudo touch /usr/local/include/ULRICH.txt 
        dtmp=$(pwd) && echo "$dtmp  atrilinos.sh"
    - name: Use Prime Numbers
      run: |
        cat /usr/local/include/ULRICH.txt
        dtmp=$(pwd) && echo "$dtmp  run.sh"
