name: Caching Primes

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Cache Primes
      id: cache-primes
      uses: actions/cache@v2
      with:
        path: Trilinos/build
        key: ${{ runner.os }}-primes
    - name: Generate Prime Numbers
      if: steps.cache-primes.outputs.cache-hit != 'true'
      run: |
        mkdir Trilinos && cd Trilinos
        mkdir build && cd build
        echo " Kawabunga " >& ULRICH.txt
        dtmp=$(pwd) && echo "$dtmp  atrilinos.sh"
    - name: Use Prime Numbers
      run: |
        cat Trilinos/build/ULRICH.txt
        dtmp=$(pwd) && echo "$dtmp  run.sh"
