name: Caching Primes

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Cache Primes
      id: cache-primes
      uses: actions/cache@v2
      with:
        path: trilinos
        key: ${{ runner.os }}-primes
    - name: Generate Prime Numbers
      if: steps.cache-primes.outputs.cache-hit != 'true'
      run: dtmp=$(pwd) && echo "$dtmp  atrilinos.sh"
    - name: Use Prime Numbers
      run: dtmp=$(pwd) && echo "$dtmp  run.sh"
