name: ubuntu-cmake
  
# Trigger the workflow on push or pull request
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      CMAKE_BUILD_TYPE: release

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      shell: bash
      run: |
           sudo apt-get update -y -qq
           sudo apt-get install -y libmetis-dev
           sudo apt-get install -y libblas-dev liblapack-dev
           sudo apt-get install -y openmpi-bin libopenmpi-dev
    - name: Download
      uses: actions/download-artifact@v1
      with:
        name: nimble_trilinos
        path: nimble_trilinos/ubuntu_trilinos.tar.gz
      if: ${{ success() }}

