name: ubuntu-cmake
  
# Trigger the workflow on push or pull request
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Install Dependencies
      shell: bash
      run: |
           sudo apt-get update -y -qq
           sudo apt-get install -y libmetis-dev
           sudo apt-get install -y libblas-dev liblapack-dev
           sudo apt-get install -y openmpi-bin libopenmpi-dev
  serial:
    runs-on: ubuntu-latest
    needs: setup
    env:
      CMAKE_BUILD_TYPE: release
    steps:
    - uses: actions/checkout@v1
    - name: Nur
      run: |
        cat trtr.sh
  mpi:
    runs-on: ubuntu-latest
    needs: setup
    env:
      CMAKE_BUILD_TYPE: release
    steps:
    - uses: actions/checkout@v1
    - name: Run
      run: |
        cat Dockerfile
