name: ubuntu-cmake
  
# Trigger the workflow on push or pull request
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Install Dependencies
      shell: bash
      run: |
           sudo apt-get update -y -qq
           sudo apt-get install -y libmetis-dev
           sudo apt-get install -y libblas-dev liblapack-dev
           sudo apt-get install -y openmpi-bin libopenmpi-dev
           git clone https://github.com/kokkos/kokkos.git
           cd kokkos
           mkdir build && cd build
           cmake .. -DKokkos_ENABLE_SERIAL=ON -DKokkos_ENABLE_OPENMP=OFF \
                -DCMAKE_INSTALL_PREFIX="/usr/"
           make && sudo make install
           ls /usr/lib/ >& e.txt
           cat e.txt
