name: ubuntu-cmake
  
# Trigger the workflow on push or pull request
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      CMAKE_BUILD_TYPE: release

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      shell: bash
      run: |
           sudo apt-get update -y -qq
           sudo apt-get install -y openmpi-bin libopenmpi-dev
           sudo apt-get install -y libmetis-dev
           sudo apt-get install -y netcdf-bin libhdf5-serial-dev libhdf5-mpich-dev
    - name: kokkos
      run: |
           git clone https://github.com/kokkos/kokkos.git
           cd kokkos && export ACCESS=`pwd`
           mkdir build && mkdir install && cd build
           cmake .. -DCMAKE_INSTALL_PREFIX="${ACCESS}/install"
           make && make install
    - name: configure
      run: |
           mkdir build && cd build
           export ACCESS=`pwd`
           cmake -DCMAKE_CXX_FLAGS="-Werror" -DUSE_PURE_MPI=ON \
                 -DHAVE_KOKKOS=ON -DKokkos_DIR="${ACCESS}/install/lib/cmake/Kokkos/" \
                 ..
    - name: build
      run: cmake --build build
    - name: test
      run: cd build && ctest

