name: PR tests (clang-8, macosx, mpich)

# Trigger the workflow on push or pull request
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: macos-10.15

    strategy:
      fail-fast: false

    env:
      CMAKE_BUILD_TYPE: release
      VT_LB_ENABLED: 1
      VT_TRACE_ENABLED: 1

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: ~/.ccache
        key: ${{ runner.os }}-macosx-clang-8-ccache-${{ hashFiles('**/*') }}
        restore-keys: |
          ${{ runner.os }}-macosx-clang-8-ccache-
    - name: Install Dependencies
      shell: bash
      run: brew bundle --file=ci/Brewfile
